### ISSUE TITLE
problem with os.rename in opus_langid

### ISSUE THREAD

**Issue by jorgtied** [Helsinki-NLP/OpusTools#9]
opus_langid throws an error if tmpdir and the file to be checked are not on the same file system. Here is the error message:

opus_langid -f FIH-SWH/xml/sv/Yle_MeMAD_013_FinSweSubs01_1/MEDIA_2015_01032469_SUBTITLE.xml -t test.xml
Traceback (most recent call last):
  File "/homeappl/home/tiedeman/.local/bin/opus_langid", line 23, in <module>
    OpusLangid(**vars(args)).processFiles()
  File "/homeappl/home/tiedeman/.local/lib/python3.4/site-packages/opustools/opus_langid.py", line 151, in processFiles
    os.rename(tempname[1], self.target_file_path)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tiedeman/tmpbs1b0mve' -> 'test.xml'

**Comment by miau1** [comment]
This is now fixed in version 1.2.3
